language: node_js
node_js: stable
addons:
  chrome: stable
script:
- npm run prepare
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        IB82a7aoWmhQRxPvkvdwGYHEIQt+bDjj415Xo8+YCl1XYST4QkJEHwPP+XgbQGmNYOlwRUnadt0VKQmfCjSJS2802mr7n939mxhqsULJ+qh2EWHZ1j6QVhIQ3BW7rpKc6PvR6ZODZz90KaezzpcMN02G51fPEFI7ZJXJr/jYa3hwuK2glctoo3w+CXP2u59MjY14p3evkkOv1S2g/4S39s0+CGoOSJi0XwzQerVMOqcImYOvTVObgS2G+n5eVb3C53zGgkJAnYq5fGZh21S2LLLjekZyApHglbU8+i2+m7drv9l1k43SFNdflN+Hwo/lbF7UWO4mfKg+fRLJm5NcFrDDb/x812FEAY98TWxzVWSPyvCWI6jDq26Svur4IWQzmtK6gwtppef90Gut0sz2GYY+I9XO0KlKYK2OK/qbAr+zEFBJOO0BNBH3JuKmKtz3Qnz+QYGnRMEb6Xeao0ChnD8dlghCmNZ+fPK6/wx+fkqd4vkHQNwm9QJ3hXz+te/bH+A5mzLBXNvbvvoQqaFYwEDpCIWjg4/xHSz+m3Ju9QZzIqLe0mZUiYwON7c8tUqCDkxfPJBrmMO7tDcGjgrVWzIPPHBGJCmRstjyc/nwJpLUcLycdX9tS7ZqxGLi0weG0gtSYkUV5kzVfxKTJ3ZeHeUAaXSdQkZdwGdjF2+nAuY=
    - secure: >-
        Xam0WNMHoAngEcS8wzl70FerqIWjrzkM2oA8SeXW73dDiXr8/Hhwu+UlRhndPWzDNcCRhml7q8em6wP5kclzDfCk7A7xboqnDtiSVJ6bFD+X8oAN/dyFm5KttWDn//jNtjhCgCy+TzflUwZB/igVtfkYaUrfhaji9HIGeF7dTNCd5GT2CMWMWFrY2aT4+xQm8DRr7p8YyHnYcAV5oNrxccVANhpkJW/rf+ydB9Udklr1u9CcCSd46wZPM2opzL0zrOTLxD5H4E9jcSx7RIHjjDB9Yv8gtjLIUi00aiG9a2/iwWLI0skeX7CbMXAjGKkue22JCH34AhQfEP9dNXL2uqY9arQ8lT/dk00ZlQ/008OFcYgH7v5nmr0QDwtY/fRuBtGCOBkMdsPjcFKMYxfSQV2SBhLK7KOhnTS0Bd1P/IO1Jyd4dyp1XnK0OWlWu2eRFAWvEIbh2mYj5tZL9epwKMRObLzhz455MLBybUrlO9gRDg5X16aTFh+48PaDqRpzeCD8d5F+xrj+S5DOfHDazFBwrv8nDFi+XPBSw303pKQrlH7RNpeHDAqjtQm5v7k4b7mYWJnURK0tla6TtkOI7EMkHhwj5gikZRr8FaLoX6vd/0CneQbGWU+q5g1+n6RwnNlZxeKKKQtAq1OQKnbEvBXMM5Jo/zfnKJFJ6ZaQOKI=
